name: daily jobs
run-name: daily jobs

on:
  schedule:
    # GitHub Actions uses UTC. 20:55 UTC == 04:55 Asia/Taipei (次日).
    - cron: "55 20 * * *"
  workflow_dispatch:

# 防重複併發（排程撞到手動）
concurrency:
  group: daily-jobs-${{ github.ref }}
  cancel-in-progress: false

# 需要能 push
permissions:
  contents: write

jobs:
  crawler-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 需要 push 回同一 repo
          persist-credentials: true
          # 取完整歷史，避免 rebase 與 tag 出錯
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Python Dependencies
        run: |
          set -euo pipefail
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping."
          fi

      - name: Download latest rar
        run: python download.py

      - name: Run main.py
        run: python3 main.py --dir data -o courses.json --pretty

      - name: Configure Git identity
        run: |
          git config --global user.name "crawler-bot"
          git config --global user.email "crawler-bot@tku.edu"
          # 部分 runner 需要宣告 safe directory
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Force commit (always, even if no changes)
        run: |
          set -euo pipefail
          git add -A || true
          git commit --allow-empty -m "daily crawl: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || true

      - name: Pull rebase and push (simple)
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git fetch origin "$BRANCH_NAME"
          git pull --rebase origin "$BRANCH_NAME"
          git push origin "HEAD:$BRANCH_NAME"
